import Image from "next/image";
import ImageLightbox from "./ImageLightbox";
import ContactForm from "./components/ContactForm";
import { assessment, consultation, services } from "./service-data";
const Button=({href,children,secondary=false}:{href:string;children:React.ReactNode;secondary?:boolean})=><a href={href} className={secondary?"btn secondary":"btn"}>{children}</a>;
export default function Home(){return <main>
<header className="nav"><a className="brand" href="#top"><b>C2U</b><span>CONNECT2U<small>DATA SOLUTIONS</small></span></a><nav><a href="/services">Services</a><a href="#proof">Evidence</a><a href="#about">About</a><Button href={consultation}>Book a consultation</Button></nav></header>
<section id="top" className="hero wrap"><div><p className="eyebrow">SQL SERVER · T-SQL · SSIS / ETL</p><h1>Slow SQL? Failing ETL?<br/><em>Data that doesn&apos;t reconcile?</em></h1><p className="lede">Connect2U helps teams diagnose and resolve high-impact SQL Server, ETL, reporting, and data-quality problems—working directly with the person doing the work.</p><div className="actions"><Button href={assessment}>Request a SQL / ETL assessment</Button><Button href="#contact" secondary>Discuss a project</Button></div><div className="proof-strip"><strong>~35%</strong><span>performance improvement delivered on a prior SQL/ETL batch-processing workload</span></div></div><Image src="/images/hero/raymond-sql-consulting-office-hero.jpg" alt="Raymond Resurreccion, Connect2U data consultant" width={900} height={1125} priority className="hero-img"/></section>
<section className="dark"><div className="wrap intro"><p className="eyebrow">FOCUSED SERVICES</p><h2>Start with the database work creating the bottleneck.</h2><p>SQL Server and ETL are the center of the practice. Power BI, Python, Snowflake, dbt, and broader data capabilities support the solution when they fit the problem.</p></div></section>
<section className="wrap section"><div className="section-head"><div><p className="eyebrow">SERVICE CATALOG</p><h2>Problem → solution → outcome</h2></div><a href="/services">Explore all services →</a></div><div className="grid">{services.slice(0,3).map((s,i)=><article className="card" key={s.slug}><ImageLightbox images={services.slice(0,3).map(service=>({src:service.image,alt:service.title}))} initialIndex={i}><Image src={s.image} alt={`${s.title} service illustration`} width={1200} height={800}/></ImageLightbox><div><span>0{i+1}</span><h3>{s.title}</h3><p><b>Problem:</b> {s.problem}</p><p><b>Solution:</b> {s.solution}</p><p><b>Outcome:</b> {s.outcome}</p><a href={`/services#${s.slug}`}>See service details →</a></div></article>)}</div></section>
<section id="proof" className="dark"><div className="wrap case"><div><p className="eyebrow">PROVEN IMPACT</p><h2>Approximately 35% faster SQL/ETL batch processing</h2><p>A prior batch-processing environment was improved by moving heavy transformations closer to the database and reducing unnecessary processing. This is relevant experience, not a guarantee that every workload will produce the same result.</p></div><div className="stat"><strong>~35%</strong><span>measured performance improvement</span><a href="/services#sql-performance">View the performance service →</a></div></div></section>
<section id="about" className="wrap section about"><Image src="/images/about/raymond-consultant-about.jpg" alt="Raymond Resurreccion of Connect2U" width={900} height={600}/><div><p className="eyebrow">DIRECT, SENIOR-LEVEL SUPPORT</p><h2>Work with Ray from first conversation through delivery.</h2><p>Connect2U is led by Raymond Resurreccion, a data professional with 15+ years of SQL and data experience. Engagements begin with the business problem, then move to the simplest reliable technical solution.</p><div className="actions"><Button href={consultation}>Book a consultation</Button><Button href="#contact" secondary>Discuss a project</Button></div></div></section>
<section id="contact" className="dark"><div className="wrap contact"><div><p className="eyebrow">LET&apos;S TALK</p><h2>Bring the bottleneck, failed load, or data question.</h2><p>You do not need to diagnose it first. Share what is happening, what you have tried, and what a useful outcome looks like.</p><p><a href="mailto:hello@connect2u.xyz">hello@connect2u.xyz</a><br/><a href="tel:+15626740039">562-674-0039</a> · call or text</p></div><ContactForm/></div></section>
<footer className="wrap footer"><span>© 2026 Connect2U Data Solutions</span><a href="/services">Services</a><a href={consultation}>Book a consultation</a></footer></main>}
