export const consultation = "mailto:hello@connect2u.xyz?subject=Book%20a%20Connect2U%20consultation";
export const assessment = "mailto:hello@connect2u.xyz?subject=SQL%20%2F%20ETL%20Assessment";
export const services = [
  { slug:"sql-performance", image:"/images/upwork/sql-performance-optimization.png", title:"SQL Server Performance Optimization", problem:"Slow queries and long-running batch jobs delay decisions and create operational risk.", solution:"Trace the bottleneck, tune T-SQL and stored procedures, and simplify the work moving through SQL Server and ETL pipelines.", outcome:"Faster, more dependable processing—with findings your team can maintain.", proof:"Prior SQL/ETL batch-processing work improved performance by approximately 35%." },
  { slug:"ssis-etl", image:"/images/upwork/ssis-etl-development-and-data-integration.png", title:"SSIS ETL & Data Integration", problem:"Fragile packages, failed loads, and disconnected systems make trusted reporting difficult.", solution:"Build, repair, or streamline SSIS workflows and the SQL transformations behind them.", outcome:"Reliable, traceable data movement with less manual intervention." },
  { slug:"tsql", image:"/images/upwork/stored-procedure-development.png", title:"SQL/T-SQL & Stored Procedure Development", problem:"Business rules buried in ad hoc queries become difficult to test, reuse, and support.", solution:"Turn them into clear T-SQL, stored procedures, views, and maintainable database routines.", outcome:"Consistent logic, easier support, and a stronger foundation for applications and reporting." },
  { slug:"reporting", image:"/images/upwork/automated-sql-reporting-and-email-distribution.png", title:"Automated SQL Reporting", problem:"Recurring reports consume hours of copying, checking, and distributing files.", solution:"Automate SQL-backed preparation and dependable report delivery around the process you actually use.", outcome:"Timelier information and fewer repetitive steps." },
  { slug:"analytics-backend", image:"/images/upwork/reporting-analytics-sql-backend.png", title:"Reporting & Analytics SQL Back-End", problem:"Dashboards cannot be trusted when definitions and source logic vary.", solution:"Create reporting-ready tables, views, and transformations that give analytics a stable back end.", outcome:"Clearer metrics and faster delivery for Power BI and other reporting tools." },
  { slug:"access-migration", image:"/images/upwork/microsoft-access-to-sql-server-migration.png", title:"Access-to-SQL Server Migration", problem:"A business-critical Access database has outgrown its users, data volume, or reliability needs.", solution:"Assess the current application and move appropriate data and logic toward SQL Server in practical stages.", outcome:"A safer, more scalable path without discarding useful business knowledge." },
  { slug:"data-quality", image:"/images/upwork/data-quality-reconciliation-and-duplicate-detection.png", title:"Data Quality, Reconciliation & Duplicate Detection", problem:"Duplicates and mismatched records undermine reporting and downstream operations.", solution:"Profile the data, define matching rules, and build repeatable reconciliation and exception workflows.", outcome:"More trustworthy records and a visible path for unresolved exceptions." },
];
